esphome:
  name: rfbridge-outprize-tx-test
  friendly_name: RF Bridge Outprize TX Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  services:
    - service: outprize_send_low24
      variables:
        low24: int
        remote_id: int
        repeats: int
      then:
        - lambda: |-
            id(rf_bridge).send_outprize_low24((uint32_t) remote_id, (uint32_t) low24, (uint8_t) repeats);

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:

external_components:
  - source: github://jfmoots/esphome_rfbridge
    components: [rfbridge]

rfbridge:
  id: rf_bridge
  cs_pin: GPIO5
  sck_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  gdo0_pin: GPIO4
  diagnostic_logging: false
  remote_id: 0x6CF

button:
  - platform: template
    name: "Outprize TX Test 40 Percent OUT"
    on_press:
      - lambda: |-
          id(rf_bridge).send_outprize_low24(0x600140, 8);

  - platform: template
    name: "Outprize TX Test Fan Off Awake"
    on_press:
      - lambda: |-
          id(rf_bridge).send_outprize_low24(0x600040, 8);

  - platform: template
    name: "Outprize TX Test Power Off"
    on_press:
      - lambda: |-
          id(rf_bridge).send_outprize_low24(0x600000, 8);

  - platform: template
    name: "Outprize TX Test 60 Percent OUT"
    on_press:
      - lambda: |-
          id(rf_bridge).send_outprize_low24(0x600340, 8);


  - platform: template
    name: "RF Replay Last Capture"
    on_press:
      - lambda: |-
          id(rf_bridge).replay_last_capture(1);

  - platform: template
    name: "RF TX Hardware Test Burst"
    on_press:
      - lambda: |-
          id(rf_bridge).send_ook_test_burst(500, 240, 8);


  - platform: template
    name: "RF TX 500ms Carrier Test"
    on_press:
      - lambda: |-
          id(rf_bridge).send_ook_carrier_test(500);
