esphome:
  name: rfbridge-outprize-tx-test
  friendly_name: RF Bridge Outprize TX Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://jfmoots/esphome_rfbridge
    components: [rfbridge]

rfbridge:
  id: rf_bridge
  cs_pin: GPIO5
  sck_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  gdo0_pin: GPIO4
  diagnostic_logging: false

button:
  - platform: template
    name: Outprize TX Test 40 Percent OUT
    on_press:
      - rfbridge.send_outprize_low24:
          id: rf_bridge
          low24: 0x600140

  - platform: template
    name: Outprize TX Test Fan Off Awake
    on_press:
      - rfbridge.send_outprize_fan_off:
          id: rf_bridge

  - platform: template
    name: Outprize TX Test Power Off
    on_press:
      - rfbridge.send_outprize_power_off:
          id: rf_bridge

  - platform: template
    name: Outprize TX Test 60 Percent OUT
    on_press:
      - rfbridge.send_outprize_low24:
          id: rf_bridge
          low24: 0x600340
          repeats: 3
