external_components:
  - source: https://github.com/jfmoots/esphome_rfbridge
    ref: main
    components: [rfbridge]

rfbridge:
  id: rf_bridge
  cs_pin: GPIO5
  sck_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  gdo0_pin: GPIO4
  gdo2_pin: GPIO27
  stx882_data_pin: GPIO26
  srx882_data_pin: GPIO25
  srx882_enable_pin: GPIO33
  remote_id: 0x6CF
  diagnostic_logging: false
  fan:
    name: "Bathroom Fan"
  vent:
    name: "Bathroom Vent"
  rain_sensor:
    name: "Bathroom Fan Rain Sensor"
  last_command_source:
    name: "Bathroom Fan Last Command Source"
